version: '3'

# 
#  * Deepseek AI
#  * author: @hootanht
#  * Under GPL-3.0 license.
#  * email: hootanhemmati@outlook.com
#  * read more at repo: https://github.com/hootanht/preconfigured-docker-compose


services:
  deepseek:
    image: deepseek/deepseek-coder:latest
    container_name: deepseek-ai
    volumes:
      - deepseek_data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped    environment:
      - MODEL_PATH=${MODEL_PATH:-/app/models}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  deepseek_data:
    name: deepseek_data
