version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    hostname: jenkins
    ports:
      - "${JENKINS_PORT:-8080}:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    env_file:
      - .env

volumes:
  jenkins_data:
