#
#  * n8n ai agent server
#  * author: @hootanht
#  * Under GPL-3.0 license.
#  * email: alisharifyofficial@gmail.com
#  * read more at repo: https://github.com/alisharify7/preconfigured-docker-compose



services:
  n8n:
    image: "n8nio/n8n:${N8N_TAG_VERSION}"
    container_name: n8n
    hostname: n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-admin}
    networks:
      - n8n_network
    env_file:
      - .env

volumes:
  n8n_data:

networks:
  n8n_network:
    driver: bridge
