# 
#  * postgres + pgadmin 
#  * author: @alisharify7
#  * Under GPL-3.0 license.
#  * email: alisharifyofficial@gmail.com
#  * read more at repo: https://github.com/alisharify7/preconfigured-docker-compose


services:
  postgres_database:
    image: 'docker.io/postgres:${POSTGRES_TAG_VERSION:-latest}' # replace latest
    container_name: postgres_db
    hostname: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}" # replace with .env
    networks:
      - internal_proxy
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - .env

  postgres_pgadmin:
    image: 'docker.io/dpage/pgadmin4:${PGADMIN_TAG_VERSION:-latest}' # replace latest
    container_name: postgres_pgadmin
    hostname: postgres_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-default@example.com}" # TODO: read from .env
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-password}"
    networks:
      - internal_proxy
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
    env_file:
      - .env
volumes:
  pg-data:
  pgadmin-data:

networks:
  internal_proxy:
