#  * jira atlasian
#  * author: @alisharify7
#  * Under GPL-3.0 license.
#  * email: alisharifyofficial@gmail.com
#  * read more at repo: https://github.com/alisharify7/preconfigured-docker-compose


services:
  jira:
    container_name: jira
    hostname: jira
    depends_on:
      - postgresql
    image: 'atlassian/jira-software:${JIRA_TAG_VERSION:-latest}'
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8001:8080'
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/jiradb'
      - 'ATL_JDBC_USER=jiradbuser'
      - 'ATL_JDBC_PASSWORD=admin'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='

  postgresql:
    container_name: postgres
    hostname: postgres
    image: 'postgres:${POSTGRES_TAG_VERSION:-latest}'
    expose:
      - '5432'
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER:-jiradbuser}'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB:-POSTGRES_DB}'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge