# 
#  * redis + redisUI 
#  * author: @alisharify7
#  * Under GPL-3.0 license.
#  * email: alisharifyofficial@gmail.com
#  * read more at repo: https://github.com/alisharify7/preconfigured-docker-compose


services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:${MSSQL_TAG:-2022-latest}
    restart: always
    environment:
      MSSQL_PID: "${MSSQL_EDITION:-Developer}"
      ACCEPT_EULA: "${ACCEPT_EULA:-Y}"
      SA_PASSWORD: "${SA_PASSWORD:-StrongPass@123}"
      MSSQL_TCP_PORT: "${MSSQL_PORT:-1433}"
    ports:
      - "${MSSQL_PORT:-1433}:${MSSQL_PORT:-1433}"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - sql_network

volumes:
  sql_data:

networks:
  sql_network: