# 
#  * postgres + pgadmin 
#  * author: @alisharify7
#  * Under GPL-3.0 license.
#  * email: alisharifyofficial@gmail.com
#  * read more at repo: https://github.com/alisharify7/preconfigured-docker-compose

services:
  postgres_live_database:
    image: 'docker.io/postgres:latest' # replace latest
    container_name: postgres_db
    hostname: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin" # replace with .env
    networks:
      - nginx_proxy
    volumes:
      - pg-data:/var/lib/postgresql/data/

  postgres_pgadmin:
    container_name: postgres_pgadmin
    image: 'docker.io/dpage/pgadmin4:latest' # replace latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.ir" # TODO: read from .env 
      PGADMIN_DEFAULT_PASSWORD: "hi:)"
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False' 
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    networks:
      - nginx_proxy
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

volumes:
  pg-data:
  pgadmin-data:

networks:
  nginx_proxy:
    external: true
    name: nginx-proxy-manager_default